apiVersion: dynatrace.com/v1beta2
kind: DynaKube
metadata:
  name: {{ .Values.global.clusterName | default (include "dynatrace.clusterName" .) }}
  namespace: dynatrace
spec:
  apiUrl: {{ include "dynatrace.apiUrl" . }}
  skipCertCheck: false
  metadataEnrichment:
    enabled: true
  oneAgent:
    cloudNativeFullStack:
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
  activeGate:
    capabilities:
      - routing
      - kubernetes-monitoring
      - dynatrace-api
    resources:
      requests:
        cpu: {{ .Values.dynakube.resources.requests.cpu }}
        memory: {{ .Values.dynakube.resources.requests.memory }}
      limits:
        cpu: {{ .Values.dynakube.resources.limits.cpu }}
        memory: {{ .Values.dynakube.resources.limits.memory }}
