apiVersion: v1
data:
  apiToken: {{ .Values.apiToken | b64enc | quote }}
  {{ if .Values.dataIngestToken }}
  dataIngestToken: {{ .Values.dataIngestToken | b64enc | quote }}
  {{ end }}
kind: Secret
metadata:
  name: {{- include "dynatrace.clusterName" . }}
  namespace: dynatrace
{{ if .Values.global.commonLabels }}
  labels:
{{- include "dynatrace.labels" . | indent 4 }}
{{ end }}
type: Opaque
