apiVersion: v1
data:
  apiToken: {{ .Values.apiToken | b64enc | quote }}
  {{ if .Values.dataIngestToken }}
  dataIngestToken: {{ .Values.dataIngestToken | b64enc | quote }}
  {{ end }}
kind: Secret
metadata:
  name: {{ .Values.global.clusterName | default (include "dynatrace.clusterName" .) }}
  namespace: dynatrace
  labels:
{{ include "dynatrace.labels" . | nindent 4 }}
type: Opaque
