apiVersion: v1
kind: ServiceAccount
metadata:
  name: siem-data-agent
  namespace: siem-data-agents
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: siem-data-agent-cluster-role
rules:
- apiGroups: [""] # "" indicates the core API group
  resources:
  - namespaces
  - pods
  - nodes
  verbs:
  - get
  - watch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: siem-data-agent-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: siem-data-agent
  namespace: siem-data-agents
roleRef:
  kind: ClusterRole
  name: siem-data-agent-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: siem-data-agent-role
  namespace: kube-system
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: siem-data-agent-role-binding
  namespace: siem-data-agents
subjects:
  - kind: ServiceAccount
    name: siem-data-agent
    namespace: siem-data-agents
roleRef:
  kind: Role
  name: siem-data-agent-role
  apiGroup: rbac.authorization.k8s.io
