global:
  clusterName: "<cluster-name>"
  # -- Labels to apply to all resources
  # @default -- the chart will add some internal labels automatically
  commonLabels: {}
  baseDomain: ""
  projectID: ""

# Please provide your Dynatrace API token and Data Ingest token below.
apiToken: "<api-token>"
dataIngestToken: "<data-ingest-token>"

dynakube:
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "1000m"
      memory: "1.5Gi"
